---
abstract: 'A modernish default lightweight logger'
author:
  - 'Kent Fredric C<kentnl@cpan.org>'
build_requires:
  Log::Contextual: '0'
  Term::ANSIColor: '2.01'
  Test::Differences: '0'
  Test::More: '0.89'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.011, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Log-Contextual-WarnLogger-Fancy
provides:
  Log::Contextual::WarnLogger::Fancy:
    file: lib/Log/Contextual/WarnLogger/Fancy.pm
    version: '0.001000'
requires:
  Term::ANSIColor: '0'
  perl: '5.006'
version: '0.001000'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
